Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.AccordionPages': ['NodeTypes/*']
    fusion:
      autoInclude:
        'Dotpulse.AccordionPages': true

Dotpulse:
  AccordionPages:
    includeCss: false
    includeJavascript: false
